server.port=8081

#quickfixj
management.endpoints.web.exposure.include=quickfixjserver

#quickfixj acceptor
management.endpoint.quickfixj.enabled=true
quickfixj.server.config=classpath:/fix/quickfixj-server.cfg
quickfixj.server.jmx-enabled=true

#quickfixj initiator
management.endpoint.quickfixjclient.enabled=true
quickfixj.client.config=classpath:/fix/quickfixj-client.cfg
quickfixj.client.jmx-enabled: true