management.endpoint.quickfixjserver.enabled=true
management.endpoints.web.exposure.include=quickfixjserver
quickfixj.server.config=${QUICKFIXJ_SERVER_CONFIG_FILE:classpath:quickfixj-server.cfg}
quickfixj.server.jmx-enabled=true
server.port=8080
api.base.url=http://localhost:8383/app/api/