server.port=8081
management.endpoint.quickfixjserver.enabled=true
management.endpoints.web.exposure.include=quickfixjserver

#Quickfixj
quickfixj.server.jmx-enabled=true
quickfixj.server.config=classpath:fix/quickfixj-server.cfg
quickfixj.server.message-store-factory=jdbc                 
quickfixj.server.log-factory=jdbc
#quickfixj.server.concurrent.enabled=true                            # whether to use a simple SocketAcceptor or a ThreadedSocketAcceptor (default: `false` - uses `SocketAcceptor`)
#quickfixj.server.concurrent.useDefaultExecutorFactory=true          # whether to use a default ExecutorFactory to create the SocketAcceptor (default: `false`)
#quickfixj.server.concurrent.queueCapacity=Integer.MAX_VALUE         # when using the default ExecutorFactory, the Executor's queue capacity (default: `Integer.MAX_VALUE`)
#quickfixj.server.concurrent.corePoolSize=8                          # when using the default ExecutorFactory, the Executor's core pool size (default: `8`)
#quickfixj.server.concurrent.maxPoolSize=Integer.MAX_VALUE           # when using the default ExecutorFactory, the Executor's max pool size (default: `Integer.MAX_VALUE`)
#quickfixj.server.concurrent.allowCoreThreadTimeOut=true             # when using the default ExecutorFactory, whether to allow core thread timeout on the Executor (default: `true`)
#quickfixj.server.concurrent.keepAliveSeconds=60                     # when using the default ExecutorFactory, the Executor's keep alive in seconds (default: `60`)
#quickfixj.server.concurrent.waitForTasksToCompleteOnShutdown=false  # when using the default ExecutorFactory, whether to wait for tasks to complete on shutdown on the Executor (default: `false`)
#quickfixj.server.concurrent.awaitTerminationSeconds=0                # when using the default ExecutorFactory, the Executor's await termination in seconds (default: `0`)


#Persistence
datasource.url=jdbc:postgresql://localhost:5432/quickfix?socketTimeout=30
datasource.username=postgres
datasource.password=postgres
datasource.hibernateShowSql=true
datasource.driver=org.postgresql.Driver
datasource.hbm2ddlAuto=validate
datasource.dialect=org.hibernate.dialect.PostgreSQL9Dialect
datasource.contextual.lob.creation=true
datasource.dbcp.maxTotalConnections=100
datasource.dbcp.maxIdleConnections=30

flyway.migration.locations=ddl
flyway.migration.table=schema_history
