server.port=8081
spring.pidfile=/opt/sosuv/pid/flowlinx-fix-server.pid
management.endpoint.quickfixjserver.enabled=true
management.endpoints.web.exposure.include=quickfixjserver

#quickfixj acceptor
#quickfixj.server.config=classpath:/fix/quickfixj-server-log.cfg
quickfixj.server.config=classpath:/fix/fix-acceptor-log.cfg
quickfixj.server.message-store-factory=jdbc
quickfixj.server.log-factory=jdbc

#quickfixj initiator
management.endpoint.quickfixjclient.enabled=true
#quickfixj.client.config=classpath:/fix/quickfixj-client-log.cfg
quickfixj.client.config=classpath:/fix/fix-initiator-log.cfg
quickfixj.client.message-store-factory=jdbc
quickfixj.client.log-factory=jdbc

#Persistence
#datasource.url=jdbc:postgresql://localhost:5432/quickfix?socketTimeout=30
#datasource.username=postgres
#datasource.password=postgres
datasource.hibernateShowSql=true
datasource.driver=org.postgresql.Driver
datasource.hbm2ddlAuto=validate
datasource.dialect=org.hibernate.dialect.PostgreSQL95Dialect
datasource.contextual.lob.creation=true
datasource.dbcp.maxTotalConnections=100
datasource.dbcp.maxIdleConnections=30

flyway.migration.locations=ddl
flyway.migration.table=schema_history

#spring boot
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

#jwt
jwt.base64-secret=ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhNwY2I4MjMxY2Y3ZmI3MjdhNI3MjdhN435678693hdybndy7My6d
jwt.token-validity-in-seconds=1200000

