server.port=8081

#quickfixj
management.endpoints.web.exposure.include=quickfixjserver

#quickfixj acceptor
management.endpoint.quickfixj.enabled=true
quickfixj.server.config=classpath:/fix/quickfixj-server-prod.cfg
quickfixj.server.jmx-enabled=true

#quickfixj initiator
management.endpoint.quickfixjclient.enabled=true
quickfixj.client.config=classpath:/fix/quickfixj-client-prod.cfg
quickfixj.client.jmx-enabled: true

#Persistence
datasource.url=jdbc:postgresql://localhost:5432/quickfix?socketTimeout=30
datasource.username=postgres
datasource.password=postgres

#auth-provider
api.auth.provider.base.url=https://api.id.flowlinx.com/